POST http://localhost:38080/v1/api/reservation/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjU0NTU3ODAsInN1YiI6IjM2NDM4NTczNzgiLCJuaWNrbmFtZSI6Iuq5gOuUlOyaqSIsImV4cCI6MTcyNTQ1NzU4MH0.h8sz1TOSETN8-KnPQZ-329imp15-MhkFrQmwuCTQui6dmdffQPMgtnE5U3b9pjMJH9oEQFgUBPKN7u5N48_6Ug

{
  "idempotencyKey": "6e65c7a2-a9b8-3aca-87af-a8df193f0d8d"
}


###
POST http://localhost:38080/v1/api/reservation/checkout
Content-Type: application/json

{


}

###

POST http://localhost:38080/v1/api/member/kakao/auth-check
Content-Type: application/json
kakaoAccessToken: AZ3NUC5coxQKgw1Obrt6EjY37TY_xvjcAAAAAQo8JFoAAAGRKwRqTOAsyCcGfplL


###

POST http://localhost:38080/v1/api/member/join
Content-Type: application/json

{
  "id": 3643857378,
  "method": "kakao",
  "name": "김디용",
  "phoneNo": "01000010001",
  "email": "test@email.com"
}

###

POST http://localhost:38080/v1/api/reservation/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjU0NTU3ODAsInN1YiI6IjM2NDM4NTczNzgiLCJuaWNrbmFtZSI6Iuq5gOuUlOyaqSIsImV4cCI6MTcyNTQ1NzU4MH0.h8sz1TOSETN8-KnPQZ-329imp15-MhkFrQmwuCTQui6dmdffQPMgtnE5U3b9pjMJH9oEQFgUBPKN7u5N48_6Ug


###